### ISSUE TITLE
compile errors under osx

### ISSUE THREAD

**Issue by krummrey** [GollyGang/ready#10]
I've been trying to compile Ready 0.7.2 using the build instructions provided. WX and VTK compile fine. Ready fails with these errors:

[ 85%] Building CXX object CMakeFiles/readybase.dir/src/readybase/AbstractRD.cpp.o
[ 85%] Building CXX object CMakeFiles/readybase.dir/src/readybase/ImageRD.cpp.o
[ 86%] Building CXX object CMakeFiles/readybase.dir/src/readybase/GrayScottImageRD.cpp.o
[ 86%] Building CXX object CMakeFiles/readybase.dir/src/readybase/OpenCLImageRD.cpp.o
/Users/jan/Downloads/ready-0.7.2/proj/reaction-diffusion-read-only/Ready/src/readybase/OpenCLImageRD.cpp:65:98: error: use of undeclared identifier 'nullptr'
        cl_int ret2 = clGetProgramBuildInfo(this->program,this->device_id,CL_PROGRAM_BUILD_LOG,0,nullptr,&build_log_length);
                                                                                                 ^
/Users/jan/Downloads/ready-0.7.2/proj/reaction-diffusion-read-only/Ready/src/readybase/OpenCLImageRD.cpp:68:130: error: use of undeclared identifier 'nullptr'
        cl_int ret3 = clGetProgramBuildInfo(this->program,this->device_id,CL_PROGRAM_BUILD_LOG,build_log_length,build_log.data(),nullptr);
                                                                                                                                 ^
/Users/jan/Downloads/ready-0.7.2/proj/reaction-diffusion-read-only/Ready/src/readybase/OpenCLImageRD.cpp:72:114: error: use of undeclared identifier 'begin'
        oss << "OpenCLImageRD::ReloadKernelIfNeeded : build failed (kernel saved as kernel.txt):\n\n" << string( begin( build_log ), end( build_log ) );
                                                                                                                 ^
/Users/jan/Downloads/ready-0.7.2/proj/reaction-diffusion-read-only/Ready/src/readybase/OpenCLImageRD.cpp:72:134: error: use of undeclared identifier 'end'
        oss << "OpenCLImageRD::ReloadKernelIfNeeded : build failed (kernel saved as kernel.txt):\n\n" << string( begin( build_log ), end( build_log ) );
                                                                                                                                     ^
4 errors generated.
make[2]: **\* [CMakeFiles/readybase.dir/src/readybase/OpenCLImageRD.cpp.o] Error 1
make[1]: **\* [CMakeFiles/readybase.dir/all] Error 2
make: **\* [all] Error 2

**Comment by timhutton** [comment]
Hi krummrey,

This code changed in July, so somehow you have an older version of the code. Is that possible? Please try with a fresh git, or with the 0.7.2 code from the releases tab.
https://github.com/GollyGang/ready/commit/c3149bf466bb10783123fbc46e29a516d9a54829

Regards,

Tim

**Comment by krummrey** [comment]
Hi Tim,
thanks for your reply. Seems that the svn checkout didn't pull version 0.7.2

After getting the right version the code compiles but the linker aborts. 
Looks like WX is broken to me. I've pasted the whole make output here:
http://pastebin.com/dttPS8AS

**Comment by danwills** [comment]
G'day Krummrey,
Not sure why you'd get an old version - maybe you said svn when you meant
git though, because the latest repo is git and is hosted on github, here:
  https://github.com/GollyGang/ready.git

I had a look at your make log, I agree it looks like something wrong with
wx.. from the main linker error: "symbol(s) not found for architecture
x86_64" it sounds like the arch of the wx that it's trying to link is
wrong.. which seems strange given that you compiled wx yourself - at least
I thought I read that up the thread, but I can't see it now.

Did you set the wx-config and wxrc vars to point to your local wx build?
Then these vars should be pointing to the corresponding binaries from
wherever your build is (you can use ccmake to do this):
  wxWidgets_CONFIG_EXECUTABLE
  wxWidgets_wxrc_EXECUTABLE

I hope that helps :)
Dan

**Comment by andykt** [comment]
krummrey:

> After getting the right version the code compiles but the linker aborts.
> Looks like WX is broken to me. ...

It seems you're using wx 3.1 (from trunk?).  Maybe try the latest stable
release which is 3.0.2.  And make sure you do a "sudo make install" after
building the wx libs -- that allows cmake to find what it needs.

I had no problems building Ready 0.7.2 on my Mac 10.6 system using
wx 3.0.2 and VTK 6.2.0.  But 10.6 uses gcc, so maybe your problems
are due to using clang on 10.9+.

Anyway, I've uploaded my 0.7.2 build to github if you want to try it.

Andrew

**Comment by krummrey** [comment]
Dan and Andrew,
thanks for your efforts. I've recompiled wx 3.0.2 and VTK and got a bunch of warnings but no errors as before. Making ready throws out the same linking error as before. Googeling the error seems related to c++. But i'm not a programmer. Just a regular guy trying to follow the build steps as outlined in BUILD.txt (which still says to use svn to get the trunk release btw.)
Andrew, I'd love to try out your 0.7.2 build, can't find it though.

**Comment by andykt** [comment]
> Andrew, I'd love to try out your 0.7.2 build, can't find it though.

Hmm, it seems you need to sign in to github to see it at the
URL below, presumably because it's a draft release:

https://github.com/GollyGang/ready/releases

I've put it on my website in case you still have trouble finding it:

http://www.trevorrow.com/ready/Ready-0.7.2-Mac.zip

Andrew

**Comment by timhutton** [comment]
Ah, the 0.7.2 release was marked as a draft, fixed. Thanks for putting the MacOSX build up, Andrew!
