### ISSUE TITLE
Keyboard shortcut help page missing

### ISSUE THREAD

**Issue by Extraltodeus** [GollyGang/ready#148]
The keyboard shortcut page is missing in the help.

**Comment by timhutton** [comment]
It is missing in the [online help](https://gollygang.github.io/ready/Help/index.html), this is true.

The reason is that we [generate that file on demand](https://github.com/GollyGang/ready/blob/c60ba37d225bac43e704fb058b1c9d3f2ee9d7cb/src/gui/HelpPanel.cpp#L320) when the user clicks on it within the help system, in order to populate it with their current choice of keyboard shortcuts:
![image](https://user-images.githubusercontent.com/647092/108276469-c8da7280-716f-11eb-8116-010ff03b27c6.png)

Possibly we can find a solution that works for both. Having the help files online was really only an afterthought.

**Comment by timhutton** [comment]
You'll notice other anomalies in the online help, such as the `open:` links in [changes.html](https://gollygang.github.io/ready/Help/changes.html). When running in Ready these open the pattern linked which is a really nice feature but not something we can easily support in the online help.

**Comment by timhutton** [comment]
I've removed the link to the online help from the front page as I think it was too problematic and the appearance was not good enough. If we find a way to produce help files that work well both inside Ready and on the web then we can put it back.
