### ISSUE TITLE
[REQ]Add FBX export option

### ISSUE THREAD

**Issue by schroef** [GollyGang/ready#27]
Would it be possible to add FBX as a export option, this format supports vertex color data. This would make importing to Blender for example much faster and way easier.

**Comment by danwills** [comment]
Good idea! Do you think it would be worth considering - perhaps as an
option, the ability to export as per-primitive data too (ie per-polygon for
a grid, per cube for 3d)? I am not certain that fbx supports it but I think
it can often lead to a better visualisation once imported without needing
to process it somehow first.
Just thinking aloud (though from some experience: We move lots of data
around between 3D apps (Houdini, Maya etc) at work (RSP))
Excellent work ye golly'ers!
Dan

**Comment by schroef** [comment]
Im not sure i get the idea of per-primitive data? Isnt this the the part where the exporter decides or states how things are exported? Depends on the mesh i think.

**Comment by danwills** [comment]
More of a decision that would be made in the exporter code: Whether to
construct geometry as a point-cloud with each point carrying the value of
one cell from the automata (connected in a grid of polygons, or not!), or
alternatively one polygon-per-cell, where each cell creates a polygon in
the FBX (which seems like it would be a square or cube in most cases, but
perhaps not for some of the other interesting tiling-modes?).

I just think it would be useful to have the option to decide which
granularity to use at export time.

Or maybe I've misunderstood the exporter, does it already only work from a
mesh? (I thought you were talking about exporting regular golly cell-based
automata sims as time-varying fbx.)

Per-point or per-polygon can be supported easily if the polygons are not
connected with each other, but that is a bit of a special case (and not
ideal since it means you have to duplicate the points for each polygon they
are a member of).
What might be better (and sounds like is supported by the FBX format) is to
emulate per-polygon values by using per-vertex (which has a value
per-point-per-polygon, so you can store all the same value within each
polygon this way.)

But yeah, have I got completely the wrong end of the stick?
Hope that helps to clarify what I was talking about :D
Dan

**Comment by schroef** [comment]
Sorry i think we didnt understand each other correct. I was talking about an export function. This is useful for other 3d applications. OBJ is very old and
